SELECT *
FROM CovidDeaths.CovidDeaths
WHERE continent is not null
ORDER BY 3, 4

SELECT *
FROM CovidVaccination.`owid-covid-data`
ORDER BY 3, 4

-- select data that we are going to be using

SELECT location, date, total_cases, new_cases, total_deaths, population
FROM CovidDeaths.CovidDeaths
ORDER BY 3, 4

-- Looking at total cases vs total deaths
-- Shows likelihood of dying if you contract covid in your country
SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES)*100 AS DEATHPERCENTAGE
FROM CovidDeaths.CovidDeaths
WHERE LOCATION LIKE '%STATES%'
ORDER BY 1, 2

-- Looking at the total cases vs population

SELECT LOCATION, DATE, POPULATION, TOTAL_CASES,(TOTAL_CASES/POPULATION)*100 AS DEATHPERCENTAGE
FROM CovidDeaths.CovidDeaths
WHERE LOCATION LIKE '%STATES%'
ORDER BY 1,2

-- Looking at countries with highest infection rate compared to population

SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT, MAX((TOTAL_CASES/POPULATION))*100 AS PERCENTPOPULATIONINFECTED
FROM CovidDeaths.CovidDeaths
GROUP BY LOCATION, POPULATION
ORDER BY PERCENTPOPULATIONINFECTED DESC

-- Showing countries with the highest death count per population

SELECT LOCATION, MAX(TOTAL_DEATHS) AS TOTALDEATHCOUNT
FROM CovidDeaths.CovidDeaths
GROUP BY LOCATION
ORDER BY TOTALDEATHCOUNT DESC

-- LET'S BREAK THINGS DOWN BY CONTINENT

-- Showing the contintent with the highest death count per population

SELECT CONTINENT, MAX(TOTAL_DEATHS) AS TOTALDEATHCOUNT
FROM CovidDeaths.CovidDeaths
WHERE  continent is not null
GROUP BY CONTINENT
ORDER BY TOTALDEATHCOUNT DESC

-- GLOBAL NUMBERS

SELECT DATE, SUM(NEW_CASES) AS TOTAL_CASES, SUM(NEW_DEATHS) AS TOTAL_DEATHS, SUM(NEW_DEATHS)/SUM(NEW_CASES)*100 AS DEATHPERCENTAGE
FROM CovidDeaths.CovidDeaths
-- WHERE LOCATION LIKE '%STATES%'
WHERE CONTINENT IS NOT NULL
GROUP BY DATE
ORDER BY 1, 2

-- Looking at total Population Vs Vaccinations

-- USE CTE
WITH POPvsVAC (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS, ROLLINGPEOPLEVACCINATED)
AS
(
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS, 
SUM(COVERT(INT,VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM CovidDeaths.CovidDeaths DEA
JOIN CovidVaccination.`owid-covid-data` VAC
	ON DEA.LOCATION = VAC.LOCATION
    AND DEA.DATE = VAC.LOCATION
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 2, 3
)
SELECT *, (ROLLINGVACCINATED/POPULATION)*100
FROM POPVSVAC


-- Creating View to store data for later visualizations

Create view PercentPopulationVaccinated as
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE, DEA.POPULATION, VAC.NEW_VACCINATIONS, 
SUM(COVERT(INT,VAC.NEW_VACCINATIONS)) OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE) AS ROLLINGPEOPLEVACCINATED
FROM CovidDeaths.CovidDeaths DEA
JOIN CovidVaccination.`owid-covid-data` VAC
	ON DEA.LOCATION = VAC.LOCATION
    AND DEA.DATE = VAC.LOCATION
WHERE DEA.CONTINENT IS NOT NULL

Select *
From PercentPopulationVaccinated

